apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: future-social-insurance-registry
resources:
  - ./deployments.yaml
  - ./services.yaml
configMapGenerator:
  - name: future-sir-frontend
    envs:
      - ./configs/config.conf
secretGenerator:
  - name: future-sir-frontend
    options:
      # disable suffix hash so we can merge
      # external secrets into this one via overlays
      disableNameSuffixHash: true
    envs:
      - ./configs/secrets.conf