apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  serviceName: redis-headless
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    #
    # pin all versions to v7.4
    #
    spec:
      initContainers:
        - name: init
          image: docker.io/redis:7.4
      containers:
        - name: redis
          image: docker.io/redis:7.4
        - name: redis-sentinel
          image: docker.io/redis:7.4