apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: future-sir-frontend
  labels:
    app.kubernetes.io/name: future-sir-frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    template:
      data:
        OTEL_AUTH_HEADER: 'Api-Token {{ .OTEL_AUTH_HEADER }}'
        REDIS_PASSWORD: '{{ .REDIS_PASSWORD }}'
        SESSION_COOKIE_SECRET: '{{ .SESSION_COOKIE_SECRET  }}'
  data:
    - secretKey: OTEL_AUTH_HEADER
      remoteRef: { key: dev, property: DT_ACCESS_TOKEN }
    - secretKey: REDIS_PASSWORD
      remoteRef: { key: shared, property: REDIS_PASSWORD }
    - secretKey: SESSION_COOKIE_SECRET
      remoteRef: { key: dev, property: SESSION_COOKIE_SECRET }
