apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: future-sir-frontend
  labels:
    app.kubernetes.io/name: future-sir-frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  data:
    - secretKey: AZUREAD_CLIENT_SECRET
      remoteRef: { key: dev, property: AZUREAD_CLIENT_SECRET }
    - secretKey: SESSION_COOKIE_SECRET
      remoteRef: { key: dev, property: SESSION_COOKIE_SECRET }
    - secretKey: REDIS_PASSWORD
      remoteRef: { key: shared, property: REDIS_PASSWORD }
