apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: future-sir-frontend
  labels:
    app.kubernetes.io/name: future-sir-frontend
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    template:
      data:
        AZUREAD_CLIENT_SECRET: '{{ .AZUREAD_CLIENT_SECRET }}'
        INTEROP_SIN_REG_API_AUTH_HEADER: 'Ocp-Apim-Subscription-Key {{ .INTEROP_API_KEY }}'
        OTEL_AUTH_HEADER: 'Api-Token {{ .DT_ACCESS_TOKEN }}'
        REDIS_PASSWORD: '{{ .REDIS_PASSWORD }}'
        SESSION_COOKIE_SECRET: '{{ .SESSION_COOKIE_SECRET  }}'
        # TODO ::: GjB ::: remove after March demo
        TMP_AWS_ID_TOKEN: '{{ .AWS_ID_TOKEN }}'
  data:
    # TODO ::: GjB ::: remove after March demo
    - secretKey: AWS_ID_TOKEN
      remoteRef: { key: int, property: AWS_ID_TOKEN }
    - secretKey: AZUREAD_CLIENT_SECRET
      remoteRef: { key: int, property: AZUREAD_CLIENT_SECRET }
    - secretKey: INTEROP_API_KEY
      remoteRef: { key: shared, property: INTEROP_API_KEY }
    - secretKey: DT_ACCESS_TOKEN
      remoteRef: { key: int, property: DT_ACCESS_TOKEN }
    - secretKey: REDIS_PASSWORD
      remoteRef: { key: shared, property: REDIS_PASSWORD }
    - secretKey: SESSION_COOKIE_SECRET
      remoteRef: { key: int, property: SESSION_COOKIE_SECRET }
