apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: future-sir-frontend
  labels:
    app.kubernetes.io/name: future-sir-frontend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    template:
      data:
        AZUREAD_CLIENT_SECRET: '{{ .AZUREAD_CLIENT_SECRET }}'
        INTEROP_API_KEY: 'Ocp-Apim-Subscription-Key {{ .INTEROP_API_KEY }}'
        OTEL_AUTH_HEADER: 'Api-Token {{ .OTEL_AUTH_HEADER }}'
        REDIS_PASSWORD: '{{ .REDIS_PASSWORD }}'
        SESSION_COOKIE_SECRET: '{{ .SESSION_COOKIE_SECRET  }}'
  data:
    - secretKey: AZUREAD_CLIENT_SECRET
      remoteRef: { key: int, property: AZUREAD_CLIENT_SECRET }
    - secretKey: INTEROP_API_KEY
      remoteRef: { key: shared, property: INTEROP_API_KEY }
    - secretKey: OTEL_AUTH_HEADER
      remoteRef: { key: int, property: DT_ACCESS_TOKEN }
    - secretKey: REDIS_PASSWORD
      remoteRef: { key: shared, property: REDIS_PASSWORD }
    - secretKey: SESSION_COOKIE_SECRET
      remoteRef: { key: int, property: SESSION_COOKIE_SECRET }
