name: Build Future SIR frontend

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-fsir-frontend.yaml
      - future-sir-frontend
  pull_request:
    branches:
     - main
    paths:
      - .github/workflows/build-fsir-frontend.yaml
      - future-sir-frontend
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-future-sir-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - run: npm clean-install
        working-directory: future-sir-frontend
      - run: npm run test -- --coverage
        working-directory: future-sir-frontend
      - run: npx playwright install --with-deps
        working-directory: future-sir-frontend
      - run: npm run test:e2e
        working-directory: future-sir-frontend
      - run: podman build --tag future-sir-frontend --file containerfile .
        working-directory: future-sir-frontend