name: PR checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.check-paths.outputs.frontend }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });

            const files = response.data.map(file => file.filename);
            const hasFrontendChanges = files.some(file => file.startsWith('future-sir-frontend/'));
            const hasGitopsChanges = files.some(file => file.startsWith('future-sir-gitops/'));
            const hasInfrastructureChanges = files.some(file => file.startsWith('future-sir-infrastructure/'));

            core.setOutput('frontend', hasFrontendChanges);
            core.setOutput('gitops', hasGitopsChanges);
            core.setOutput('infrastructure', hasInfrastructureChanges);

  build-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/build-fsir-frontend.yaml

  scan-frontend:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/scan-fsir-frontend.yaml
