name: Scan Future SIR frontend

on:
  workflow_call: {}
  workflow_dispatch: {}

env:
  CI: true

jobs:
  scan-future-sir-frontend:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      packages: read
    steps:
    - uses: actions/checkout@v4
    - uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
    - uses: github/codeql-action/analyze@v3
      with:
        category: /language:javascript-typescript
